// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/sumitsj/url-shortener/models"
)

// UrlMappingRepository is an autogenerated mock type for the UrlMappingRepository type
type UrlMappingRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: urlMapping
func (_m *UrlMappingRepository) Create(urlMapping *models.URLMapping) error {
	ret := _m.Called(urlMapping)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.URLMapping) error); ok {
		r0 = rf(urlMapping)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUrlMappingRepository creates a new instance of UrlMappingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUrlMappingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UrlMappingRepository {
	mock := &UrlMappingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
